# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170604_0608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coupons',
            new_name='coupon',
        ),
    ]
