# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20170604_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='food',
            field=models.CharField(choices=[('bigmac', '大麥克'), ('chicken', '勁辣雞腿堡')], max_length=50),
        ),
    ]
