# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20170604_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='food',
            field=models.CharField(choices=[('大麥克', 'BigMac'), ('勁辣雞腿堡', 'Spicy chicken filet')], max_length=50),
        ),
    ]
