# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20170604_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='image',
            field=models.ImageField(height_field='height', null=True, upload_to='', width_field='width'),
        ),
    ]
