# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_remove_coupon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
