# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20170605_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='target',
        ),
        migrations.DeleteModel(
            name='following',
        ),
    ]
