# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20170605_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='food',
            field=models.CharField(choices=[('麥香魚', 'Fillet_O_Fish'), ('中薯', 'French_Fries'), ('麥克雞塊', 'McNugget')], max_length=50),
        ),
    ]
