# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20170605_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='food',
            field=models.CharField(choices=[('Fillet_O_Fish', '麥香魚'), ('French_Fries', '中薯'), ('McNugget', '麥克雞塊')], max_length=50),
        ),
    ]
