# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 04:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bank_id_first',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bank_id_last',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Required. digits and +-() only.', max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+()-]+$', 'Enter a valid phone number.', 'invalid')], verbose_name='home phone number'),
        ),
    ]
