# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20170604_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='food',
            field=models.CharField(blank=True, choices=[('bigmac', 'bigmac'), ('chicken', 'chicken')], max_length=50),
        ),
    ]
