# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20170604_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='food',
            field=models.CharField(choices=[('BigMac', '大麥克'), ('SpicyChickenFilet', '勁辣雞腿堡'), ('FrenchFries', '大薯條')], max_length=50),
        ),
    ]
