# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_coupon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='image',
        ),
    ]
