# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20170605_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Following',
            new_name='Mcfollowing',
        ),
    ]
