# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20170605_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
