# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20170605_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='food',
            field=models.CharField(choices=[('Spicy_chicken_filet', '勁辣雞腿堡 買一送一'), ('French_Fries', '大薯 買一送一'), ('McFlurry', '冰炫風'), ('Happy_sticker', '歡樂貼')], max_length=50),
        ),
    ]
